apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infinicache-node-39
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/serverless-research-274508/infinicache-node
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
