apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinicache-node-deployment
spec:
  selector:
    matchLabels:
      app: infinicache-node
  replicas: 2
  template:
    metadata:
      labels:
        app: infinicache-node
    spec:
      containers:
      - name: infinicache-node
        image: gcr.io/fraudio/infinicache-node
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
          - containerPort: 4000
            name: hello-port