apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infinicache-node-4
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/serverless-research-274508/infinicache-node
          ports:
            - containerPort: 8080
