apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infinicache-node-19
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/fraudio/infinicache-node
