#!/bin/bash

export KNATIVE_VERSION="0.16.0"

export ISTIO_VERSION="1.5.4"

export PROJECT_ID="serverless-research274508"

export CLUSTER_NAME="infinicache-cluster"

export CLUSTER_REGION="europe-west4"

export CLUSTER_ZONE="${CLUSTER_REGION}-a"

export CLUSTER_START_NODE_SIZE=4

export CLUSTER_MAX_NODE_SIZE=10

export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"

export CLUSTER_MASTER_VERSION="latest"