#!/bin/bash

set -v

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install Serving CRDs
kubectl apply -f "https://github.com/knative/serving/releases/download/v${KNATIVE_VERSION}/serving-crds.yaml"

# Install Serving Core Components
kubectl apply -f "https://github.com/knative/serving/releases/download/v${KNATIVE_VERSION}/serving-core.yaml"

